import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { describe, expect, it, vi } from 'vitest'
import { createGenerationService, GenerationService } from './GenerationService'

describe('GenerationService', () => {
	it('stores generated bytes under canvas/assets and returns a local URL', async () => {
		const canvasDirectory = await mkdtemp(path.join(os.tmpdir(), 'localart-generation-'))
		const comfyClient = {
			generate: vi.fn(async () => ({
				promptId: 'prompt-1',
				filename: 'remote.png',
				mimeType: 'image/png',
				imageBytes: new Uint8Array([1, 2, 3]),
			})),
		}
		const service = new GenerationService({
			canvasDirectory,
			comfyClient,
			createId: () => 'asset-1',
		})

		const result = await service.generate('make it cinematic')

		expect(result).toEqual({
			assetId: 'asset-1',
			url: '/assets/asset-1.png',
			promptId: 'prompt-1',
		})
		expect(
			new Uint8Array(await readFile(path.join(canvasDirectory, 'assets', 'asset-1.png')))
		).toEqual(new Uint8Array([1, 2, 3]))
	})
})

describe('createGenerationService', () => {
	it('loads the configured API workflow', async () => {
		const directory = await mkdtemp(path.join(os.tmpdir(), 'localart-workflow-'))
		const workflowPath = path.join(directory, 'workflow.json')
		await writeFile(
			workflowPath,
			JSON.stringify({
				'6': { class_type: 'CLIPTextEncode', inputs: { text: 'old' } },
			})
		)

		const service = await createGenerationService({
			baseUrl: 'http://comfy.test',
			workflowPath,
			promptNodeId: '6',
			canvasDirectory: path.join(directory, 'canvas'),
			fetchImplementation: vi.fn(),
		})

		expect(service).toBeInstanceOf(GenerationService)
	})
})
